feat(seatmap): configurable seat width
KRRUg/KLMS pull request #116
Opened 2023-12-07 22:41 UTC by maxmarkus

- style settings for table size, table aspect ratio, border radius and seat size, seating distance
- proper multiple-seat-creation calculation respecting width + distance
- kill duplicate seat-creation modal xhrs (eg on double right-click or slow connection)
- sneak in: for /content/ routes, [allow dashes in slugs](https://github.com/KRRUg/KLMS/pull/116/commits/8394d605428143bf1aeb1329de3335b3c6caf9ab#diff-975333add6f5949b81a576e69b655b18df4b2aef7bdbf95c7b308223a276b3d6R31) 

Example for non-standard table size:
<img width="500" alt="Bildschirmfoto 2023-12-07 um 23 27 55" src="https://github.com/KRRUg/KLMS/assets/1720843/6d133492-4d0a-48bb-829d-d6048ee61c42">

2023-12-08 02:56 UTC, Ovascos commented
The new tables look good :)
But please separate your docker/doc changes from the front-end changes.
Furthermore, I didn't see anything about content routes in your changes.

2023-12-08 08:07 UTC, maxmarkus commented
oh, I didn't want to commit those docker changes. should have revisited my pr 🙈

2023-12-09 06:02 UTC, Ovascos requested changes

2023-12-09 06:02 UTC, Ovascos commented on templates/admin/seatmap/index.html.twig
> +                Lade einen Grundriss hoch um den Sitzplan zu erstellen: <a href="/admin/setting/edit?key=lan.seatmap.bg_image">Zu den Einstellungen</a>
use `path('admin_setting_edit', {'key': 'lan.seatmap.bg_image'})` instead of the hard-coded URL.

2023-12-09 06:02 UTC, Ovascos commented on src/Service/SettingService.php
> +            if ($default) {
Whenever calling `get('id', false)` or `get('id', 0)` for an unset id, the static default value is incorrectly returned instead of the passed default value.
Better use `$default = null` in the function parameter list and `return !is_null($default) ? $default : self::getDefaultValue($key);`

2023-12-09 06:02 UTC, Ovascos commented on templates/admin/seatmap/index.html.twig
> +            {% if settings.get('lan.seatmap.styles.seat_border_radius', 10) %}
With the default value in SettingService, is there still a need for the if?
Is there a reason for another default value for `seat_boarder_radius` at this place?

2023-12-10 19:06 UTC, maxmarkus commented on templates/admin/seatmap/index.html.twig
> +                Lade einen Grundriss hoch um den Sitzplan zu erstellen: <a href="/admin/setting/edit?key=lan.seatmap.bg_image">Zu den Einstellungen</a>
Ah, didn't realize the second param when trying smth similar. Thanks for pointing out.

2023-12-10 19:08 UTC, maxmarkus commented on templates/admin/seatmap/index.html.twig
> +            {% if settings.get('lan.seatmap.styles.seat_border_radius', 10) %}
Right. We can get rid of them alltogether, since we rely only on the service values now.

2023-12-10 20:02 UTC, Ovascos approved these changes
LGTM

2023-12-10 20:03 UTC, merged